import {
  iconService,
  iconSaloon,
  iconMarketing,
  iconInsurance,
  iconFood,
  iconAdmin,
  iconConstruction,
  iconDelivery,
  iconEntertainment,
  iconGovernment,
  iconHome,
  iconAuto,
  iconLaw,
  iconManagement,
  iconFinance,
  iconSale,
  iconScience,
  iconSecurity,
  iconStudent,
  iconHr,
  iconMedicine,
  iconFactory,
  iconPurchase,
  iconBank,
  iconIt,
  iconConsulting,
} from "../icons/categoryIcons";

export default [
  {
    name: "Автомобильный бизнес",
    transliteratedName: "avtomobilnyj-biznes",
    icon: iconAuto,
  },
  {
    name: "Административная работа",
    transliteratedName: "administrativnaja-rabota",
    icon: iconAdmin,
  },
  {
    name: "Банки, инвестиции",
    transliteratedName: "banki-investicii",
    icon: iconBank,
  },
  {
    name: "Охрана, безопасность",
    transliteratedName: "ohrana-bezopasnost",
    icon: iconSecurity,
  },
  {
    name: "Бухгалтерия, финансы",
    transliteratedName: "buhgalterija-finansy",
    icon: iconFinance,
  },
  {
    name: "Высший менеджмент",
    transliteratedName: "vysshij-menedzhment",
    icon: iconManagement,
  },
  {
    name: "Госслужба, НКО",
    transliteratedName: "gossluzhba-NKO",
    icon: iconGovernment,
  },
  {
    name: "Домашний персонал",
    transliteratedName: "domashnij-personal",
    icon: iconHome,
  },
  { name: "Закупки", transliteratedName: "zakupki", icon: iconPurchase },
  {
    name: "IT, интернет, телеком",
    transliteratedName: "IT-internet-telekom",
    icon: iconIt,
  },
  {
    name: "Искусство, развлечения",
    transliteratedName: "iskusstvo-razvlechenija",
    icon: iconEntertainment,
  },
  {
    name: "Консультирование",
    transliteratedName: "konsultirovanie",
    icon: iconConsulting,
  },
  {
    name: "Маркетинг, реклама, PR",
    transliteratedName: "marketing-reklama-pr",
    icon: iconMarketing,
  },
  {
    name: "Медицина, фармацевтика",
    transliteratedName: "medicina-marmacevtika",
    icon: iconMedicine,
  },
  {
    name: "Образование, наука",
    transliteratedName: "obrazovanie-nauka",
    icon: iconScience,
  },
  {
    name: "Без опыта, студенты",
    transliteratedName: "bez-opyta-studenty",
    icon: iconStudent,
  },
  {
    name: "Продажи",
    transliteratedName: "prodazhi",
    icon: iconSale,
  },
  {
    name: "Производство, сырьё, с/х",
    transliteratedName: "Proizvodstvo-syrjo",
    icon: iconFactory,
  },
  {
    name: "ЖКХ, эксплуатация",
    transliteratedName: "hZhKH-jekspluatacija",
    icon: iconService,
  },
  {
    name: "Фитнес, салоны красоты",
    transliteratedName: "fitnes-salony-krasoty",
    icon: iconSaloon,
  },
  {
    name: "Страхование",
    transliteratedName: "strahovanie",
    icon: iconInsurance,
  },
  {
    name: "Строительство",
    transliteratedName: "stroitelstvo",
    icon: iconConstruction,
  },
  {
    name: "Транспорт, логистика",
    transliteratedName: "transport-logistika",
    icon: iconDelivery,
  },
  {
    name: "Туризм, рестораны",
    transliteratedName: "turizm-restorany",
    icon: iconFood,
  },
  {
    name: "Управление персоналом",
    transliteratedName: "upravlenie-personalom",
    icon: iconHr,
  },
  {
    name: "Юриспруденция",
    transliteratedName: "jurisprudencija",
    icon: iconLaw,
  },
];
