const JobCategories = [
  {
    name: "Hospitality and Tourism",
    subCategories: [
      "Banquet Manager",
      "Event Manager",
      "Event Planner",
      "Floral Designer",
      "Greeter",
      "Guest Service Agent",
      "Housekeeper",
      "Travel Agent",
    ],
  },
  {
    name: "Retail and Sales",
    subCategories: [
      "Account Executive",
      "Account Manager",
      "Account Representative",
      "Business Development Manager",
      "Business Development Specialist",
      "Director Of Business Development",
      "Director Of Sales",
      "District Sales Manager",
      "Field Representative",
      "Inside Sales Representative",
      "Key Account Manager",
      "Merchandiser",
      "National Account Manager",
      "National Sales Manager",
      "Outside Sales Representative",
      "Regional Sales Manager",
      "Retail Merchandiser",
      "Route Sales Representative",
      "Sales Associate",
      "Sales Consultant",
      "Sales Coordinator",
      "Sales Executive",
      "Sales Manager",
      "Sales Representative",
      "Sales Specialist",
      "Telemarketer",
      "Trader",
      "VP of Sales",
      "Cashier",
      "Esthetician",
      "Assistant Store Manager",
      "Jeweler",
      "Head Cashier",
      "Representative Retail Sales",
      "Store Manager",
    ],
  },
  {
    name: "Industrial and Manufacturing",
    subCategories: [
      "Assembler",
      "Autocad Drafter",
      "Chemist",
      "Drafter",
      "Machine Operator",
      "Production Worker",
    ],
  },
  {
    name: "Transportation and Logistics",
    subCategories: [
      "Construction Manager",
      "Construction Superintendent",
      "Construction Worker",
      "Custodian",
      "Electrician",
      "Facilities Manager",
    ],
  },
  {
    name: "Accounting and Finance",
    subCategories: [
      "Accountant",
      "Accounting Assistant",
      "Accounting Clerk",
      "Billing Specialist",
      "Bookkeeper",
      "Budget Analyst",
      "Controller",
      "Director Of Finance",
      "Finance Manager",
      "Financial Advisor",
      "Financial Analyst",
      "Financial Associate",
      "Financial Reporting Manager",
      "Full Charge Bookkeeper",
      "Internal Auditor",
      "Night Auditor",
      "Quantitative Analyst",
      "Senior Accountant",
      "Tax Accountant",
      "Tax Manager",
      "Treasury Analyst",
      "VP Director of Finance",
      "VP of Finance",
    ],
  },
  {
    name: "Healthcare",
    subCategories: [
      "Case Manager",
      "Dental Assistant",
      "Dental Hygienist",
      "Director of Nursing",
      "Health Unit Coordinator",
      "Home Health Aide",
      "Massage Therapist",
      "Medical Assistant",
      "Medical Receptionist",
      "Medical Technologist",
      "Medical Worker",
      "Nuclear Medicine Technologist",
      "Nurse",
      "Nurse Assistant",
      "Nursing Assistant",
      "Nutritionist",
      "Physical Therapist",
      "Social Worker",
      "Unit Clerk",
    ],
  },
  {
    name: "Arts and Entertainment",
    subCategories: [
      "Designer",
      "Editor",
      "Graphic Artist",
      "Graphics Designer",
      "Illustrator",
      "Journalist",
      "Photographer",
      "User Interface Designer",
      "Video Editor",
      "Writer",
      "Art Director",
    ],
  },
];

module.exports = {
  JobCategories,
};
